const cervezasHuichahue = [

                // Array con las cervezas del catalogo.

        {
            id: 1,
            nombre: 'Pilsen',
            seo: 'Cerveza artesanal Tradicional sabor Pilsen',
            categoria: 'Tradicional',
            descripcion: 'Cerveza rubia, persistente espuma blanca y fina burbuja. Chispeante al paladar, plena de sabor y refrescante, de buen amargor.',
            grados: '4,5',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Pilsen.jpg'},
        {
            id: 2,
            nombre: 'Imperial Stout',
            seo: 'Cerveza artesanal Tradicional sabor Imperial Stout ',
            categoria: 'Tradicional',
            descripcion: 'Cerveza Negra con notas ahumadas, café, chocolate y cacao. Cuerpo sedoso al paladar y amargor medio.',
            grados: '9,0',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0ImperialStout.jpg',
        },
        {
            id: 3,
            nombre: 'Amber Ale',
            seo: 'Cerveza artesanal Tradicional sabor Amber Ale',
            categoria: 'Tradicional',
            descripcion: 'Genera una experiencia única en olor y sabor. Espuma consistente. Buen balance entre amargor medio y dulzor final. Se caracteriza por sus notas florales con un color ámbar rojizo. En boca se puede percibir el sabor a lúpulo moderado, con un equilibrio de malta caramelo que persiste hasta el final.',
            grados: '5,3',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0AmberAle.jpg',
        },
        {
            id: 4,
            nombre: 'Arandano',
            seo: 'Cerveza artesanal Frutal sabor Arandano',
            categoria: 'Frutal',
            descripcion: 'Refrescante, con suaves notas a lúpulo y malta. Cuenta con arándanos, debido a sus excelentes propiedades antioxidantes y su alto contenido en la importante vitamina C. Llama la atención por su suave dulzor, su color y su intenso aroma.',
            grados: '5,3',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Arandanos.jpg',
        },
        {
            id: 5,
            nombre: 'Maqui',
            seo: 'Cerveza artesanal Frutal sabor Maqui ',
            categoria: 'Frutal',
            descripcion: 'Cerveza elaborada con maqui, cuenta con propiedades antioxidantes, antiinflamatorias e incluso contribuye a quemar grasas. Cerveza especial que otorga una sensación suave y refrescante, finalizando en un amargor suave.',
            grados: '5,3',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Maqui.jpg',
        },
        {
            id: 6,
            nombre: 'Frambuesa',
            seo: 'Cerveza artesanal Frutal sabor Frambuesa ',
            categoria: 'Frutal',
            descripcion: 'Cerveza suave, dulce y refrescante debido a los azúcares naturales de las frambuesas, combina el sabor de una excelente cerveza con el dulzor y sabor de la fruta.',
            grados: '5,0',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Frambuesa.jpg',
        },
        {
            id: 7,
            nombre: 'Moras',
            seo: 'Cerveza artesanal Frutal sabor Mora ',
            categoria: 'Frutal',
            descripcion: 'Cerveza que destaca por su sabor refrescante con el fruto de la zarza que invade nuestros bosques y campos, la mora.',
            grados: '4,8',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Moras.jpg',
        },
        {
            id: 8,
            nombre: 'Calafate',
            seo: 'Cerveza artesanal Frutal sabor Calafate ',
            categoria: 'Frutal',
            descripcion: 'Cerveza tipo Ale, con sabor y aroma intenso a Calafate, que además te entrega notas finales de maltas tostadas. Fermentada y madurada con Calafate y Michay.',
            grados: '5,0',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Calafate.jpg',
        },
        {
            id: 9,
            nombre: 'Piñones',
            seo: 'Cerveza artesanal Experimental sabor Piñones ',
            categoria: 'Experimental',
            descripcion: 'Es una cerveza refrescante, liviana pero sabrosa, en la que resaltan las maltas sobre el lúpulo, con sabor a piñón, el ingrediente estrella, recolectado a mano en nuestra Araucanía Andina. La mezcla refleja el poder sagrado del Pehuén (Araucaria Araucana), árbol milenario cuyo fruto ha sido el alimento que ha dado vida a la Araucanía de Chile.',
            grados: '5,0',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Pinones.jpg',
        },
        {
            id: 10,
            nombre: 'Aji cacho de cabra',
            seo: 'Cerveza artesanal Experimental sabor Aji cacho de cabra  ',
            categoria: 'Experimental',
            descripcion: 'La mezcla perfecta entre una dominante cerveza negra y un rebelde Ají Cacho de Cabra Ahumado. Resaltan sus notas de pimienta, café y madera con el Ají Cacho de Cabra, que le entrega un aroma ahumado y un pequeño picor.',
            grados: '4,5',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0Aji.jpg',
        },
        {
            id: 11,
            nombre: 'Kombuchela Natural',
            seo: 'Cerveza artesanal sin alcohol con Kombucha',
            categoria: 'Kombuchela',
            descripcion: 'Elaborada de manera colaborativa entre Kombucha Trecena y Cerveza Huichahue. Bebida de té negro fermentado ácido con levadura de cerveza, tiene contenido probiótico, es apta para celíacos, y con una alta incidencia de vitaminas B, ofrece los beneficios funcionales de la Kombucha tradicional, al mismo tiempo que ofrece un intenso y fresco sabor a Cerveza, generado a través del lúpulo en flor que se le ha agregado.',
            grados: 'Cerveza sin alcohol',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '../../../public/ImagenTienda/0KombuTradi.jpg',
        },
        {
            id: 12,
            nombre: 'Kombuchela Miel',
            seo: 'Cerveza artesanal sin alcohol con Kombucha sabor Miel',
            categoria: 'Kombuchela',
            descripcion: 'Elaborada de manera colaborativa entre Kombucha Trecena y Cerveza Huichahue. Bebida de té negro fermentado ácido con levadura de cerveza, tiene contenido probiótico, es apta para celíacos, y con una alta incidencia de vitaminas B, ofrece los beneficios funcionales de la Kombucha tradicional, al mismo tiempo que ofrece un intenso y fresco sabor a Cerveza. Ésta variedad contiene Miel de apicultores de la zona.',
            grados: 'Cerveza sin alcohol',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '',
        },
        {
            id: 13,
            nombre: 'Kombuchela Chocolate',
            seo: 'Cerveza artesanal sin alcohol com Kombuche sabor Cacao ',
            categoria: 'Kombuchela',
            descripcion: 'Elaborada de manera colaborativa entre Kombucha Trecena y Cerveza Huichahue. Bebida de té negro fermentado ácido con levadura de cerveza, tiene contenido probiótico, es apta para celíacos, y con una alta incidencia de vitaminas B, ofrece los beneficios funcionales de la Kombucha tradicional, al mismo tiempo que ofrece un intenso y fresco sabor a Cerveza. Ésta variedad contiene un elegante toque a Cacao que le entrega un sabor final a Chocolate.',
            grados: 'Cerveza sin alcohol',
            precio: '3000',
            formato: '330cc',
            enStock: true,
            Imagen: '',
        },
        {
            id: 14,
            nombre: 'Pack de 6 Cervezas artesanales',
            seo: 'Pack de cervezas artesanales mix de sabores ',
            categoria: 'Pack',
            descripcion: 'Pack de 6 cervezas artesanales, mix de sabores para degustar',
            precio: '15.000',
            formato: '6 x 330cc',
            enStock: true,
            Imagen: '',
        },
        {
            id: 15, 
            nombre: 'Pack 6 Kombuchela',
            seo: 'Pack de Kombuchela artesanal cerveza sin alcohol y kombucha ',
            categoria: 'Pack',
            descripcion: 'Pack de Kombuchela, cerveza sin alcohol elaborada en conjunto a Kombucha trecena, mix de sabores. ',
            precio: '15.000',
            formato: '6 x 330cc',
            enStock: true,
            Imagen: '',
        },
        {
            id: 16,
            nombre: 'Pack 12 Cervezas artesanales',
            seo: 'Cerveza artesanal ',
            categoria: 'Pack',
            descripcion: 'Pack de 12 cervezas artesanales, mix de sabores para degustar',
            precio: '30.000',
            formato: '12 x 330cc',
            enStock: true,
            Imagen: '',
        },
    ]

export {cervezasHuichahue}